version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  printscriptapi:
    image: my-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    secrets:
      - username
      - token

secrets:
  username:
    file: ./secrets/username
  token:
    file: ./secrets/token
volumes:
  postgres_data: