version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env

  printscriptapi:
    image: ghcr.io/ingsismege/printscriptapi:latest.snapshot
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    secrets:
      - username
      - token

  api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8081:8081"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

secrets:
  username:
    file: ./secrets/username
  token:
    file: ./secrets/token
volumes:
  postgres_data:
  blob: