name: CI

on:
  push:

  pull_request:
    branches:
      - dev
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Create.env file
        run: |
          echo "BUCKET_URL="Hello"" >> .env
          echo "RULE_URL=""LOL"" >> .env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build





